
core:
  Database: App\Core\Database
  Session: App\Core\Session

service:
  SecurityService: App\Service\SecurityService
  CompteService: App\Service\CompteService
  TransactionService: App\Service\TransactionService

repository:
  PersonneRepository: App\Repository\PersonneRepository
  CompteRepository: App\Repository\CompteRepository
  TransactionRepository: App\Repository\TransactionRepository

